# Day 4: Intro to Pandas Data Structure

It's only the fourth day but I feel like I have learned a lot already. So, the next lesson is Pandas. I'm a bit familiar with this as I've used this a couple of times already. I'm sure there is still a lot to learn.

In [24]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

For pandas, there are two most important data structures: Series and DataFrame.

## Series

In [3]:
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [13]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [15]:
obj2['a']

-5

In [18]:
obj2['d'] = 6

In [19]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

NumPy array operations will preserve the index-value link.

In [20]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [21]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [22]:
obj * 2

0     8
1    14
2   -10
3     6
d    12
dtype: int64

In [25]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

A Series can be represented as a fixed-length, ordered dict, since it is a mapping of index values to data values.

In [26]:
'b' in obj2

True

In [27]:
'e' in obj2

False

In [28]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [29]:
obj3 = Series(sdata)

In [30]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [31]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [32]:
obj4 = Series(sdata, index=states)

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

To check for missing or NA data values, you can use the functions isnull and notnull.

In [34]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [35]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [36]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

The Series data structure also automatically aligns differently-indexed data in arithmetic operations.

In [37]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [38]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [39]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

You can specify the name of the object itself and its indices.

In [40]:
obj4.name = 'population'

In [41]:
obj4.index.name = 'state'

In [42]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [44]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan', 'Justin']

In [45]:
obj

Bob       4
Steve     7
Jeff     -5
Ryan      3
Justin    6
dtype: int64

## DataFrame

A dataframe represents a tabular, spreadsheet-like data structure containing an ordered group of columns. It can be accessed using its row or column indices.

In [46]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [48]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [49]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [51]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [54]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [53]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [57]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [58]:
frame2['debt'] = 16.5

In [59]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [60]:
frame2['debt'] = np.arange(5.)

In [61]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [62]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [63]:
frame2['debt'] = val

In [65]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [67]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [68]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

NOTE: The del keyword will delete columns.

In [69]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [70]:
frame3 = DataFrame(pop)

In [71]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [72]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [73]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [74]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [75]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [77]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [78]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

## Index Objects

In [79]:
obj = Series(range(3), index=['a', 'b', 'c'])

In [82]:
index = obj.index

In [83]:
index

Index(['a', 'b', 'c'], dtype='object')

In [84]:
index[1:]

Index(['b', 'c'], dtype='object')

Note: Index objects are immutable.

In [85]:
index = pd.Index(np.arange(3))

In [86]:
obj2 = Series([1.5, -2.5, 0], index=index)

In [87]:
obj2.index is index

True

In [88]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [89]:
'Ohio' in frame3.columns

True

In [90]:
2003 in frame3.index

False

Other index methods and properties include: append, diff, intersection, union, isin, delete, drop, insert, is_monotonic, is_unique, and unique.